openapi: 3.0.0
info:
  title: API
  description: API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost
paths:
  $ref: './paths/index.yml'
components:
  $ref: './components/index.yml'
